FROM kallikrein/ubuntu:14.04
MAINTAINER kallikrein <thomas.charlat@gmail.com>

RUN apt-get install -y qbittorrent-nox

VOLUME /root/.config/qBittorrent
VOLUME /root/.local/share/data/qBittorrent
VOLUME /root/Downloads
