FROM kallikrein/sails:0.12.0

MAINTAINER Thomas Charlat "thomas.charlat@gmail.com"

RUN npm i -g \
  sails-generate-policy \
  sails-generate-response \
  sails-generate-generator \
  sails-generate-adapter
