FROM ubuntu:14.04

MAINTAINER Thomas Charlat "thomas.charlat@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get update && \
  apt-get install -y software-properties-common curl git htop man wget make python g++

CMD ["bash"]
