FROM kallikrein/ubuntu:14.04

MAINTAINER Thomas Charlat "thomas.charlat@gmail.com"

RUN curl https://nodejs.org/dist/v5.5.0/node-v5.5.0-linux-x64.tar.gz | tar xz -C /usr/local/ --strip=1

VOLUME /src
WORKDIR /src
