FROM kallikrein/ubuntu:14.04
MAINTAINER Thomas Charlat

# install node
RUN curl http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz | tar xz -C /usr/local/ --strip=1

VOLUME /src
WORKDIR /src