FROM kallikrein/ubuntu:14.04
MAINTAINER Thomas Charlat

# install node
RUN curl https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-x64.tar.gz | tar xz -C /usr/local/ --strip=1

VOLUME /src
WORKDIR /src
